description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4.1.0
      with:
        version: 8
    - uses: actions/setup-node@v4.3.0
      with:
        node-version: '18.x'
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite